// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: proto/calculater/calculater.proto

package calculater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 一维
type Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float32 `protobuf:"fixed32,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *Array) Reset() {
	*x = Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{0}
}

func (x *Array) GetValue() []float32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ArrayInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []int64 `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *ArrayInt) Reset() {
	*x = ArrayInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayInt) ProtoMessage() {}

func (x *ArrayInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayInt.ProtoReflect.Descriptor instead.
func (*ArrayInt) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{1}
}

func (x *ArrayInt) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

// 二维
type Matrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array []*Array `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
}

func (x *Matrix) Reset() {
	*x = Matrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix) ProtoMessage() {}

func (x *Matrix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix.ProtoReflect.Descriptor instead.
func (*Matrix) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{2}
}

func (x *Matrix) GetArray() []*Array {
	if x != nil {
		return x.Array
	}
	return nil
}

type MatrixInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array []*ArrayInt `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
}

func (x *MatrixInt) Reset() {
	*x = MatrixInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixInt) ProtoMessage() {}

func (x *MatrixInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixInt.ProtoReflect.Descriptor instead.
func (*MatrixInt) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{3}
}

func (x *MatrixInt) GetArray() []*ArrayInt {
	if x != nil {
		return x.Array
	}
	return nil
}

type MatrixComplex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RealArray []*Array `protobuf:"bytes,1,rep,name=real_array,json=realArray,proto3" json:"real_array,omitempty"`
	ImagArray []*Array `protobuf:"bytes,2,rep,name=imag_array,json=imagArray,proto3" json:"imag_array,omitempty"`
}

func (x *MatrixComplex) Reset() {
	*x = MatrixComplex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixComplex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixComplex) ProtoMessage() {}

func (x *MatrixComplex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixComplex.ProtoReflect.Descriptor instead.
func (*MatrixComplex) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{4}
}

func (x *MatrixComplex) GetRealArray() []*Array {
	if x != nil {
		return x.RealArray
	}
	return nil
}

func (x *MatrixComplex) GetImagArray() []*Array {
	if x != nil {
		return x.ImagArray
	}
	return nil
}

// 三维
type Tensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matrix []*Matrix `protobuf:"bytes,1,rep,name=matrix,proto3" json:"matrix,omitempty"`
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{5}
}

func (x *Tensor) GetMatrix() []*Matrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

// 四维
type BszTensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tensor []*Tensor `protobuf:"bytes,1,rep,name=tensor,proto3" json:"tensor,omitempty"`
}

func (x *BszTensor) Reset() {
	*x = BszTensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BszTensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BszTensor) ProtoMessage() {}

func (x *BszTensor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BszTensor.ProtoReflect.Descriptor instead.
func (*BszTensor) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{6}
}

func (x *BszTensor) GetTensor() []*Tensor {
	if x != nil {
		return x.Tensor
	}
	return nil
}

type GetModelByPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetModelByPathRequest) Reset() {
	*x = GetModelByPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelByPathRequest) ProtoMessage() {}

func (x *GetModelByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelByPathRequest.ProtoReflect.Descriptor instead.
func (*GetModelByPathRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{7}
}

type GetModelByPathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matrix []*CombinedMatrix `protobuf:"bytes,1,rep,name=matrix,proto3" json:"matrix,omitempty"`
}

func (x *GetModelByPathResponse) Reset() {
	*x = GetModelByPathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelByPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelByPathResponse) ProtoMessage() {}

func (x *GetModelByPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelByPathResponse.ProtoReflect.Descriptor instead.
func (*GetModelByPathResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{8}
}

func (x *GetModelByPathResponse) GetMatrix() []*CombinedMatrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

type EncodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartPos int64    `protobuf:"varint,1,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	Input    []string `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
}

func (x *EncodeRequest) Reset() {
	*x = EncodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeRequest) ProtoMessage() {}

func (x *EncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeRequest.ProtoReflect.Descriptor instead.
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{9}
}

func (x *EncodeRequest) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *EncodeRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

type EncodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartPos int64      `protobuf:"varint,1,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	Tokens   *MatrixInt `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{10}
}

func (x *EncodeResponse) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *EncodeResponse) GetTokens() *MatrixInt {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CombinedMatrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CombinedMatrix) Reset() {
	*x = CombinedMatrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombinedMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedMatrix) ProtoMessage() {}

func (x *CombinedMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedMatrix.ProtoReflect.Descriptor instead.
func (*CombinedMatrix) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{11}
}

func (x *CombinedMatrix) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CombinedMatrix) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PreProcessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartPos int64      `protobuf:"varint,1,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	Tokens   *MatrixInt `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *PreProcessRequest) Reset() {
	*x = PreProcessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreProcessRequest) ProtoMessage() {}

func (x *PreProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreProcessRequest.ProtoReflect.Descriptor instead.
func (*PreProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{12}
}

func (x *PreProcessRequest) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *PreProcessRequest) GetTokens() *MatrixInt {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type PreProcessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartPos int64          `protobuf:"varint,1,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	H        *Tensor        `protobuf:"bytes,2,opt,name=h,proto3" json:"h,omitempty"`
	FreqsCis *MatrixComplex `protobuf:"bytes,3,opt,name=freqs_cis,json=freqsCis,proto3" json:"freqs_cis,omitempty"`
	Mask     *Matrix        `protobuf:"bytes,4,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *PreProcessResponse) Reset() {
	*x = PreProcessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreProcessResponse) ProtoMessage() {}

func (x *PreProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreProcessResponse.ProtoReflect.Descriptor instead.
func (*PreProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{13}
}

func (x *PreProcessResponse) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *PreProcessResponse) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *PreProcessResponse) GetFreqsCis() *MatrixComplex {
	if x != nil {
		return x.FreqsCis
	}
	return nil
}

func (x *PreProcessResponse) GetMask() *Matrix {
	if x != nil {
		return x.Mask
	}
	return nil
}

type RotrayEmbRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I        int64          `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	StartPos int64          `protobuf:"varint,2,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	H        *Tensor        `protobuf:"bytes,3,opt,name=h,proto3" json:"h,omitempty"`
	Xq       *BszTensor     `protobuf:"bytes,4,opt,name=xq,proto3" json:"xq,omitempty"`
	Xk       *BszTensor     `protobuf:"bytes,5,opt,name=xk,proto3" json:"xk,omitempty"`
	Xv       *BszTensor     `protobuf:"bytes,6,opt,name=xv,proto3" json:"xv,omitempty"`
	FreqsCis *MatrixComplex `protobuf:"bytes,7,opt,name=freqs_cis,json=freqsCis,proto3" json:"freqs_cis,omitempty"`
}

func (x *RotrayEmbRequest) Reset() {
	*x = RotrayEmbRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotrayEmbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotrayEmbRequest) ProtoMessage() {}

func (x *RotrayEmbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotrayEmbRequest.ProtoReflect.Descriptor instead.
func (*RotrayEmbRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{14}
}

func (x *RotrayEmbRequest) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *RotrayEmbRequest) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *RotrayEmbRequest) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *RotrayEmbRequest) GetXq() *BszTensor {
	if x != nil {
		return x.Xq
	}
	return nil
}

func (x *RotrayEmbRequest) GetXk() *BszTensor {
	if x != nil {
		return x.Xk
	}
	return nil
}

func (x *RotrayEmbRequest) GetXv() *BszTensor {
	if x != nil {
		return x.Xv
	}
	return nil
}

func (x *RotrayEmbRequest) GetFreqsCis() *MatrixComplex {
	if x != nil {
		return x.FreqsCis
	}
	return nil
}

type RotrayEmbResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xq *BszTensor `protobuf:"bytes,1,opt,name=xq,proto3" json:"xq,omitempty"`
	Xk *BszTensor `protobuf:"bytes,2,opt,name=xk,proto3" json:"xk,omitempty"`
	Xv *BszTensor `protobuf:"bytes,3,opt,name=xv,proto3" json:"xv,omitempty"`
}

func (x *RotrayEmbResponse) Reset() {
	*x = RotrayEmbResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotrayEmbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotrayEmbResponse) ProtoMessage() {}

func (x *RotrayEmbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotrayEmbResponse.ProtoReflect.Descriptor instead.
func (*RotrayEmbResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{15}
}

func (x *RotrayEmbResponse) GetXq() *BszTensor {
	if x != nil {
		return x.Xq
	}
	return nil
}

func (x *RotrayEmbResponse) GetXk() *BszTensor {
	if x != nil {
		return x.Xk
	}
	return nil
}

func (x *RotrayEmbResponse) GetXv() *BszTensor {
	if x != nil {
		return x.Xv
	}
	return nil
}

type LoadModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{16}
}

func (x *LoadModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadModelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadModelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{17}
}

type ScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bsz    int64      `protobuf:"varint,1,opt,name=bsz,proto3" json:"bsz,omitempty"`
	Seqlen int64      `protobuf:"varint,2,opt,name=seqlen,proto3" json:"seqlen,omitempty"`
	Name   string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Xq     *BszTensor `protobuf:"bytes,4,opt,name=xq,proto3" json:"xq,omitempty"`
	Xk     *BszTensor `protobuf:"bytes,5,opt,name=xk,proto3" json:"xk,omitempty"`
	Xv     *BszTensor `protobuf:"bytes,6,opt,name=xv,proto3" json:"xv,omitempty"`
	Mask   *Matrix    `protobuf:"bytes,7,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{18}
}

func (x *ScoreRequest) GetBsz() int64 {
	if x != nil {
		return x.Bsz
	}
	return 0
}

func (x *ScoreRequest) GetSeqlen() int64 {
	if x != nil {
		return x.Seqlen
	}
	return 0
}

func (x *ScoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScoreRequest) GetXq() *BszTensor {
	if x != nil {
		return x.Xq
	}
	return nil
}

func (x *ScoreRequest) GetXk() *BszTensor {
	if x != nil {
		return x.Xk
	}
	return nil
}

func (x *ScoreRequest) GetXv() *BszTensor {
	if x != nil {
		return x.Xv
	}
	return nil
}

func (x *ScoreRequest) GetMask() *Matrix {
	if x != nil {
		return x.Mask
	}
	return nil
}

type ScoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Tensor `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{19}
}

func (x *ScoreResponse) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

type ProjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	H    *Tensor `protobuf:"bytes,2,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *ProjRequest) Reset() {
	*x = ProjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjRequest) ProtoMessage() {}

func (x *ProjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjRequest.ProtoReflect.Descriptor instead.
func (*ProjRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{20}
}

func (x *ProjRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjRequest) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

type ProjResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *BszTensor `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *ProjResponse) Reset() {
	*x = ProjResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjResponse) ProtoMessage() {}

func (x *ProjResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjResponse.ProtoReflect.Descriptor instead.
func (*ProjResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{21}
}

func (x *ProjResponse) GetX() *BszTensor {
	if x != nil {
		return x.X
	}
	return nil
}

type FeedForwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	H    *Tensor `protobuf:"bytes,2,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *FeedForwardRequest) Reset() {
	*x = FeedForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedForwardRequest) ProtoMessage() {}

func (x *FeedForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedForwardRequest.ProtoReflect.Descriptor instead.
func (*FeedForwardRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{22}
}

func (x *FeedForwardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedForwardRequest) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

type FeedForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Tensor `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *FeedForwardResponse) Reset() {
	*x = FeedForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedForwardResponse) ProtoMessage() {}

func (x *FeedForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedForwardResponse.ProtoReflect.Descriptor instead.
func (*FeedForwardResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{23}
}

func (x *FeedForwardResponse) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

type OutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H *Tensor `protobuf:"bytes,2,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *OutRequest) Reset() {
	*x = OutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutRequest) ProtoMessage() {}

func (x *OutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutRequest.ProtoReflect.Descriptor instead.
func (*OutRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{24}
}

func (x *OutRequest) GetH() *Tensor {
	if x != nil {
		return x.H
	}
	return nil
}

type OutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output *Matrix `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *OutResponse) Reset() {
	*x = OutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_calculater_calculater_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutResponse) ProtoMessage() {}

func (x *OutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculater_calculater_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutResponse.ProtoReflect.Descriptor instead.
func (*OutResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculater_calculater_proto_rawDescGZIP(), []int{25}
}

func (x *OutResponse) GetOutput() *Matrix {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_proto_calculater_calculater_proto protoreflect.FileDescriptor

var file_proto_calculater_calculater_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x22,
	0x1d, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20,
	0x0a, 0x08, 0x41, 0x72, 0x72, 0x61, 0x79, 0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x31, 0x0a, 0x06, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x27, 0x0a, 0x05, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x22, 0x37, 0x0a, 0x09, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x49, 0x6e, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x49, 0x6e, 0x74, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x22, 0x73, 0x0a, 0x0d,
	0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x12, 0x30, 0x0a,
	0x0a, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x30, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72,
	0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x22, 0x34, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x6d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52,
	0x06, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x22, 0x37, 0x0a, 0x09, 0x42, 0x73, 0x7a, 0x54, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x72, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52,
	0x06, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x22, 0x42, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x5c, 0x0a, 0x0e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x49, 0x6e,
	0x74, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x43, 0x6f, 0x6d,
	0x62, 0x69, 0x6e, 0x65, 0x64, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x5f, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x49, 0x6e, 0x74, 0x52, 0x06, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72,
	0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x01, 0x68, 0x12, 0x36, 0x0a, 0x09, 0x66, 0x72,
	0x65, 0x71, 0x73, 0x5f, 0x63, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x52, 0x08, 0x66, 0x72, 0x65, 0x71, 0x73, 0x43,
	0x69, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61,
	0x74, 0x72, 0x69, 0x78, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x8c, 0x02, 0x0a, 0x10, 0x52,
	0x6f, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x69, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x73, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x01, 0x68, 0x12, 0x25, 0x0a, 0x02,
	0x78, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52,
	0x02, 0x78, 0x71, 0x12, 0x25, 0x0a, 0x02, 0x78, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a,
	0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02, 0x78, 0x6b, 0x12, 0x25, 0x0a, 0x02, 0x78, 0x76,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02, 0x78,
	0x76, 0x12, 0x36, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x73, 0x5f, 0x63, 0x69, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x52,
	0x08, 0x66, 0x72, 0x65, 0x71, 0x73, 0x43, 0x69, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x11, 0x52, 0x6f,
	0x74, 0x72, 0x61, 0x79, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x02, 0x78, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x52, 0x02, 0x78, 0x71, 0x12, 0x25, 0x0a, 0x02, 0x78, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02, 0x78, 0x6b, 0x12, 0x25, 0x0a,
	0x02, 0x78, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x52, 0x02, 0x78, 0x76, 0x22, 0x3a, 0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x13, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe9, 0x01, 0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x73, 0x7a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x62, 0x73, 0x7a, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6c,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6c, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x02, 0x78, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73,
	0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02, 0x78, 0x71, 0x12, 0x25, 0x0a, 0x02, 0x78,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02,
	0x78, 0x6b, 0x12, 0x25, 0x0a, 0x02, 0x78, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x02, 0x78, 0x76, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x22, 0x31, 0x0a, 0x0d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x52, 0x01, 0x68, 0x22, 0x43, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6a, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x01, 0x68, 0x22, 0x33, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x72, 0x2e, 0x42, 0x73, 0x7a, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x01, 0x78, 0x22, 0x4a,
	0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72,
	0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x01, 0x68, 0x22, 0x37, 0x0a, 0x13, 0x46, 0x65,
	0x65, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x52, 0x01, 0x68, 0x22, 0x2e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x01, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x52, 0x01, 0x68, 0x22, 0x39, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x32, 0x88,
	0x05, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x12, 0x57, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x21, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x19, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x72, 0x2e, 0x50, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x52, 0x6f, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6d,
	0x62, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x52,
	0x6f, 0x74, 0x72, 0x61, 0x79, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x74,
	0x72, 0x61, 0x79, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48,
	0x0a, 0x09, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1c, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x50, 0x72, 0x6f, 0x6a,
	0x12, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x03, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x75,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x6f, 0x66, 0x2f, 0x6a, 0x6f,
	0x62, 0x73, 0x2d, 0x66, 0x6f, 0x72, 0x2d, 0x74, 0x68, 0x65, 0x2d, 0x62, 0x6f, 0x79, 0x73, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_calculater_calculater_proto_rawDescOnce sync.Once
	file_proto_calculater_calculater_proto_rawDescData = file_proto_calculater_calculater_proto_rawDesc
)

func file_proto_calculater_calculater_proto_rawDescGZIP() []byte {
	file_proto_calculater_calculater_proto_rawDescOnce.Do(func() {
		file_proto_calculater_calculater_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_calculater_calculater_proto_rawDescData)
	})
	return file_proto_calculater_calculater_proto_rawDescData
}

var file_proto_calculater_calculater_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_calculater_calculater_proto_goTypes = []interface{}{
	(*Array)(nil),                  // 0: calculater.Array
	(*ArrayInt)(nil),               // 1: calculater.ArrayInt
	(*Matrix)(nil),                 // 2: calculater.Matrix
	(*MatrixInt)(nil),              // 3: calculater.MatrixInt
	(*MatrixComplex)(nil),          // 4: calculater.MatrixComplex
	(*Tensor)(nil),                 // 5: calculater.Tensor
	(*BszTensor)(nil),              // 6: calculater.BszTensor
	(*GetModelByPathRequest)(nil),  // 7: calculater.GetModelByPathRequest
	(*GetModelByPathResponse)(nil), // 8: calculater.GetModelByPathResponse
	(*EncodeRequest)(nil),          // 9: calculater.EncodeRequest
	(*EncodeResponse)(nil),         // 10: calculater.EncodeResponse
	(*CombinedMatrix)(nil),         // 11: calculater.CombinedMatrix
	(*PreProcessRequest)(nil),      // 12: calculater.PreProcessRequest
	(*PreProcessResponse)(nil),     // 13: calculater.PreProcessResponse
	(*RotrayEmbRequest)(nil),       // 14: calculater.RotrayEmbRequest
	(*RotrayEmbResponse)(nil),      // 15: calculater.RotrayEmbResponse
	(*LoadModelRequest)(nil),       // 16: calculater.LoadModelRequest
	(*LoadModelResponse)(nil),      // 17: calculater.LoadModelResponse
	(*ScoreRequest)(nil),           // 18: calculater.ScoreRequest
	(*ScoreResponse)(nil),          // 19: calculater.ScoreResponse
	(*ProjRequest)(nil),            // 20: calculater.ProjRequest
	(*ProjResponse)(nil),           // 21: calculater.ProjResponse
	(*FeedForwardRequest)(nil),     // 22: calculater.FeedForwardRequest
	(*FeedForwardResponse)(nil),    // 23: calculater.FeedForwardResponse
	(*OutRequest)(nil),             // 24: calculater.OutRequest
	(*OutResponse)(nil),            // 25: calculater.OutResponse
}
var file_proto_calculater_calculater_proto_depIdxs = []int32{
	0,  // 0: calculater.Matrix.array:type_name -> calculater.Array
	1,  // 1: calculater.MatrixInt.array:type_name -> calculater.ArrayInt
	0,  // 2: calculater.MatrixComplex.real_array:type_name -> calculater.Array
	0,  // 3: calculater.MatrixComplex.imag_array:type_name -> calculater.Array
	2,  // 4: calculater.Tensor.matrix:type_name -> calculater.Matrix
	5,  // 5: calculater.BszTensor.tensor:type_name -> calculater.Tensor
	11, // 6: calculater.GetModelByPathResponse.matrix:type_name -> calculater.CombinedMatrix
	3,  // 7: calculater.EncodeResponse.tokens:type_name -> calculater.MatrixInt
	3,  // 8: calculater.PreProcessRequest.tokens:type_name -> calculater.MatrixInt
	5,  // 9: calculater.PreProcessResponse.h:type_name -> calculater.Tensor
	4,  // 10: calculater.PreProcessResponse.freqs_cis:type_name -> calculater.MatrixComplex
	2,  // 11: calculater.PreProcessResponse.mask:type_name -> calculater.Matrix
	5,  // 12: calculater.RotrayEmbRequest.h:type_name -> calculater.Tensor
	6,  // 13: calculater.RotrayEmbRequest.xq:type_name -> calculater.BszTensor
	6,  // 14: calculater.RotrayEmbRequest.xk:type_name -> calculater.BszTensor
	6,  // 15: calculater.RotrayEmbRequest.xv:type_name -> calculater.BszTensor
	4,  // 16: calculater.RotrayEmbRequest.freqs_cis:type_name -> calculater.MatrixComplex
	6,  // 17: calculater.RotrayEmbResponse.xq:type_name -> calculater.BszTensor
	6,  // 18: calculater.RotrayEmbResponse.xk:type_name -> calculater.BszTensor
	6,  // 19: calculater.RotrayEmbResponse.xv:type_name -> calculater.BszTensor
	6,  // 20: calculater.ScoreRequest.xq:type_name -> calculater.BszTensor
	6,  // 21: calculater.ScoreRequest.xk:type_name -> calculater.BszTensor
	6,  // 22: calculater.ScoreRequest.xv:type_name -> calculater.BszTensor
	2,  // 23: calculater.ScoreRequest.mask:type_name -> calculater.Matrix
	5,  // 24: calculater.ScoreResponse.h:type_name -> calculater.Tensor
	5,  // 25: calculater.ProjRequest.h:type_name -> calculater.Tensor
	6,  // 26: calculater.ProjResponse.x:type_name -> calculater.BszTensor
	5,  // 27: calculater.FeedForwardRequest.h:type_name -> calculater.Tensor
	5,  // 28: calculater.FeedForwardResponse.h:type_name -> calculater.Tensor
	5,  // 29: calculater.OutRequest.h:type_name -> calculater.Tensor
	2,  // 30: calculater.OutResponse.output:type_name -> calculater.Matrix
	7,  // 31: calculater.Calculater.GetModelByPath:input_type -> calculater.GetModelByPathRequest
	9,  // 32: calculater.Calculater.Encode:input_type -> calculater.EncodeRequest
	12, // 33: calculater.Calculater.PreProcess:input_type -> calculater.PreProcessRequest
	14, // 34: calculater.Calculater.RotrayEmb:input_type -> calculater.RotrayEmbRequest
	16, // 35: calculater.Calculater.LoadModel:input_type -> calculater.LoadModelRequest
	20, // 36: calculater.Calculater.Proj:input_type -> calculater.ProjRequest
	18, // 37: calculater.Calculater.Score:input_type -> calculater.ScoreRequest
	22, // 38: calculater.Calculater.FeedForward:input_type -> calculater.FeedForwardRequest
	24, // 39: calculater.Calculater.Out:input_type -> calculater.OutRequest
	8,  // 40: calculater.Calculater.GetModelByPath:output_type -> calculater.GetModelByPathResponse
	10, // 41: calculater.Calculater.Encode:output_type -> calculater.EncodeResponse
	13, // 42: calculater.Calculater.PreProcess:output_type -> calculater.PreProcessResponse
	15, // 43: calculater.Calculater.RotrayEmb:output_type -> calculater.RotrayEmbResponse
	17, // 44: calculater.Calculater.LoadModel:output_type -> calculater.LoadModelResponse
	21, // 45: calculater.Calculater.Proj:output_type -> calculater.ProjResponse
	19, // 46: calculater.Calculater.Score:output_type -> calculater.ScoreResponse
	23, // 47: calculater.Calculater.FeedForward:output_type -> calculater.FeedForwardResponse
	25, // 48: calculater.Calculater.Out:output_type -> calculater.OutResponse
	40, // [40:49] is the sub-list for method output_type
	31, // [31:40] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_calculater_calculater_proto_init() }
func file_proto_calculater_calculater_proto_init() {
	if File_proto_calculater_calculater_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_calculater_calculater_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Matrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixComplex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BszTensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelByPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelByPathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CombinedMatrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreProcessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreProcessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotrayEmbRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotrayEmbResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadModelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_calculater_calculater_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_calculater_calculater_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculater_calculater_proto_goTypes,
		DependencyIndexes: file_proto_calculater_calculater_proto_depIdxs,
		MessageInfos:      file_proto_calculater_calculater_proto_msgTypes,
	}.Build()
	File_proto_calculater_calculater_proto = out.File
	file_proto_calculater_calculater_proto_rawDesc = nil
	file_proto_calculater_calculater_proto_goTypes = nil
	file_proto_calculater_calculater_proto_depIdxs = nil
}
